# Generated by Django 3.2.8 on 2021-10-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_bondadditionalinfo_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondadditionalinfo',
            name='gov_reg_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bondadditionalinfo',
            name='list_level',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bondadditionalinfo',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
