# Generated by Django 3.2.8 on 2021-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20211025_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondadditionalinfo',
            name='maturity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bondadditionalinfo',
            name='next_coupon_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
