# Generated by Django 3.2.8 on 2021-10-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20211025_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredquotes',
            name='ticker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quote.quote'),
        ),
    ]
