# Generated by Django 3.2.8 on 2021-10-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_featuredquotes_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredquotes',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.ticker'),
        ),
    ]
