# Generated by Django 3.2.8 on 2021-10-27 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_alter_featuredquotes_ticker'),
        ('trading_strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField(default=0)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.ticker')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.timeframe')),
                ('trading_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_strategy.tradingstrategy')),
            ],
        ),
    ]
