# Generated by Django 3.2.8 on 2021-10-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_alter_featuredquotes_ticker'),
        ('trading_strategy', '0002_signals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signals',
            new_name='Signal',
        ),
    ]
